export class Supplier {
    constructor(
        public id: number, 
        public supplierName: string,
        public clientAccount: string,
        public sterlingReference: string,
        public supplierType: string,
        public alternativeReference: string,        
        public assignee: string,
        public postalCode: string,
        public country: string,
        public addressLine1: string,
        public addressLine2: string,
        public town: string,
        public state: string,
        public supplierContact: string,
        public telephone: string,
        public fax: string,
        public mobile: string,
        public email: string,
        public currency: string,
        public defaultVATRate: string,
        public VATRegisterNumber: string,
        public defaultGLCode: string,
        public supplierPrefix: string,
        public supplierDescriptionType: string,
        public paymentTerms: string,
        public paymentType: string,
        public accountNumber: string,
        public sortCode: string,
        public supplierRemittance: string,
        public status: string,
        public approvedBy: string,
        public approvedDate: string,
        public suspendedBy: string,
        public suspendedDate: string,
        public rejectedBy: string,
        public rejectedDate: string
    ) { 
    }
 }